### ISSUE TITLE
jQuery Datatable

### ISSUE THREAD

**Issue by androyt1** [mosh-hamedani/vidly-mvc-5#16]
jQuery Datatable not​showing up..I mean using this $("#customers"). DataTable();
Has anyone passed this... please help

**Comment by devashrayee** [comment]
Hi I had the same issue than realized the typo in my bundles. Please check the spellings.

**Comment by androyt1** [comment]
Thanks apiguru... sorted it out...my table was malformed.. Thanks again​

**Comment by apiguru** [comment]
No worries also the data parameter is case sensitive and the element we are feeding to datatable must match the exact name along with any caps alphabet.

**Comment by iHamzaKhanzada** [comment]
@androyt1 , if you have resolved the issue, please mark this as closed

**Comment by androyt1** [comment]
Thanks everyone
