### ISSUE TITLE
Movie with 2 character length not shown in the suggestion to add a movie for rental 

### ISSUE THREAD

**Issue by rajakishore** [mosh-hamedani/vidly-mvc-5#2]
![image](https://cloud.githubusercontent.com/assets/20180690/16405619/ae3bdf8a-3d3b-11e6-8df7-ca4a20c3957f.png)

Movie with 2 character length not shown in the suggestion to add a movie for rental by customer.

Thanks Mosh for this wonderful course.

**Comment by nerdyrasa** [comment]
In the rental view, change minLength to 2. It is currently set at 3, so that's why a movie with a length of 2 is not shown:

$('#movie').typeahead({
                minLength: 3,  
                highlight: true
            },

**Comment by rajakishore** [comment]
Thanks for your time.
Got it!!

**Comment by IamBashir** [comment]
Hi, i am new to MVC i started this Online course 2weeks ago and i got this error "The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.Movies_dbo.Genres_GenreId". The conflict occurred in database "aspnet-Mosh-20170127111411", table "dbo.Genres", column 'Id'.
The statement has been terminated." when i  was trying to Update my Movie. can you please be of help?

**Comment by iHamzaKhanzada** [comment]
@IamBashir , Make sure you have records in Genres table and you are passing the appropriate GenreId while updating a movie, it seems like while inserting a movie, you either don't have records in genres table or you are passing invalid genreid while creating a movie. Please check

**Comment by iHamzaKhanzada** [comment]
@rajakishore  please mark the issue as closed if you have resolved this
