### ISSUE TITLE
glimpse install 

### ISSUE THREAD

**Issue by DimitraK92** [mosh-hamedani/vidly-mvc-5#212]
i got this error while trying to install glimpse

PM> install-package glimse.mvc5
install-package : Unable to find package 'glimse.mvc5'
At line:1 char:1
+ install-package glimse.mvc5
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception

**Comment by leilaMortezaiFar** [comment]
you forget p in glimpse
>instll-package glimpse.mvs5

**Comment by DimitraK92** [comment]
ok that was embarrassing. I guess I was extremely dizzy. Thank you very much and I'm sorry for opening a whole issue for this!!!!
