### ISSUE TITLE
DataTables warning: table id=movies - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by Razvan30** [mosh-hamedani/vidly-mvc-5#50]
Please Help me! I try for few hours to solve this error but no result... I search for internet this error to solve it but not any result...Any sugestions are helpful.... Thanks!
![capturetableerrormovie](https://user-images.githubusercontent.com/20680575/44958704-992a4800-aeec-11e8-8655-d2843eacb7f1.PNG)
![capturetableerrormovie1](https://user-images.githubusercontent.com/20680575/44958705-992a4800-aeec-11e8-8082-8166929d19aa.PNG)
![capturetablemovieconsoleerror](https://user-images.githubusercontent.com/20680575/44958706-992a4800-aeec-11e8-824e-8fa0d624006e.PNG)

**Comment by Razvan30** [comment]
$(document).ready(function () {
            var table = $("#movies").DataTable({
                ajax: {

                    url: "/api/Movies",
                    dataSrc: "",

                },
                columns: [
                    {
                        data: "name",
                        render: function (data, type, movie) {
                            return "<a href='/movies/edit/" + movie.id + "'>" + movie.name + "</a>";
                        }
                    },
                    {
                        data: "genre.name"
                    },
                    {
                        data: "id",
                        render: function (data) {
                            return "<button class='btn-link js-delete' data-movie-id=" + data + ">Delete</button>";
                        }
                    }
                ]
            });


            $("#movies").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure you want to delete this movie?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/movies/" + button.attr("data-movie-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });
        });

**Comment by Razvan30** [comment]
I saw that my table Movie is not exist in database. I tried to update database but appear the error "Invalid column name 'Birthdate'."  and i don't know  to fix this error

**Comment by Razvan30** [comment]
![captureerror1](https://user-images.githubusercontent.com/20680575/45176066-99da1b80-b217-11e8-9207-2edc759dfb06.PNG)

**Comment by Razvan30** [comment]
I solve this isssue... the error It was in MappingProfile.css 

Mapper.CreateMap<Personal, PersonalDto>();
            Mapper.CreateMap<Movie, MovieDto>();
            Mapper.CreateMap<MembershipType, MembershipTypeDto>();
            Mapper.CreateMap<Genre, GenreDto>();


            // Dto to Domain
            Mapper.CreateMap<PersonalDto, Personal>()
                .ForMember(c => c.Id, opt => opt.Ignore());

            Mapper.CreateMap<MovieDto, Movie>()
               .ForMember(c => c.Id, opt => opt.Ignore());

**Comment by muhammedgamal30** [comment]
i still don't know how to solve this problem ... any help ????
