### ISSUE TITLE
Postman rest client update customer error (The property 'Id' is part of the object's key information and cannot be modified.)

### ISSUE THREAD

**Issue by A7medDaoud** [mosh-hamedani/vidly-mvc-5#65]

**Comment by RizwanTariq** [comment]
i also facing same problem do you got the solution?

**Comment by RizwanTariq** [comment]
i got the solution replace
Mapper.Map(customerInDto, customerInDb)   with
var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            customerInDb.Name = customer.Name;
            customerInDb.Birthdate = customer.Birthdate;
            customerInDb.IsSubscribedToNewsletter = customer.IsSubscribedToNewsletter;
            customerInDb.MembershipTypeId = customer.MembershipTypeId;
