### ISSUE TITLE
Compiler Error Message: CS1503: Argument 1: cannot convert from 'Video_Rental.Models.MembershipType' to 'System.Collections.IEnumerable'

### ISSUE THREAD

**Issue by vc94** [mosh-hamedani/vidly-mvc-5#7]
@Html.DropDownListFor(m => m.Customer.MembershipType, new SelectList(Model.Customer.MembershipType , "Id", "Name"), "Select Membership Type", new { @class = "form-control" })

i m getting error at this line can you please help me to clear this

**Comment by KeilCarpenter** [comment]
You should be calling the primary key of the MembershipType object which is MembershipTypeId

@Html.DropDownListFor(m => m.Customer.MembershipTypeId, new SelectList(Model.MembershipTypes, "Id", "Name"), "Select Membership Type", new { @class = "form-control" })

**Comment by iHamzaKhanzada** [comment]
Hello @vc94 , please mark the issue as closed as @KeilCarpenter  has explained you the error
