### ISSUE TITLE
Create database error

### ISSUE THREAD

**Issue by BAGHERIFarzad** [mosh-hamedani/vidly-mvc-5#88]
![Capture](https://user-images.githubusercontent.com/56923236/69759136-a1118000-1161-11ea-8677-41f91afa78d7.PNG)
Anyone have a idea pls

**Comment by BAGHERIFarzad** [comment]
When i run update-database , i got this error

**Comment by leosch92** [comment]
Took me a couple of hours to figure this out:

If you **clone or fork** the project, the Folder App_Data will not be uploaded from git. You need to manually create the folder in the file system, in your project folder.

Also, you probably have to change Data Source from connectionStrings, as mentioned in #8

**Comment by BAGHERIFarzad** [comment]
Thanks bro , this error is for a long time ago and sorry i didnt close that and thank you for take a time to look at my error. in my case after save the file and close the VS and reopen the solution all the things works.
